First release deployment updates
raccoongang/askup pull request #12
Opened 2018-02-23 15:19 UTC by KhaimovMR

2018-02-23 19:41 UTC, rimikt commented
@KhaimovMR 
1. Assign Reviewer
2. Assign Assignee - yourself

First time will do it for you.

2018-02-23 19:43 UTC, rimikt commented
@KhaimovMR 
Where is a description?
I see commit with comment - `change from DevOps`. So where is changes from DevOps?
PR is empty.
Will review without any details.

2018-02-23 20:54 UTC, cmltaWt0 requested changes

2018-02-23 20:54 UTC, cmltaWt0 commented on deploy-clean.sh
> +cd `dirname $(readlink -f $0)`/.dc-$DCENV
I can't the script.
```
➜  askup git:(khaimovmr/deploy-fixes) ./deploy-clean.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./deploy-clean.sh: line 9: cd: /.dc-dev: No such file or directory
Such environment isn't defined
```

2018-02-23 20:54 UTC, cmltaWt0 commented on deploy-clean.sh
> +sudo rm -rf .volumes
Why do you need `sudo` privileges here?

2018-02-23 20:54 UTC, cmltaWt0 commented on deploy-clean.sh
> +sudo docker-compose build && sudo docker-compose up -d
Same as above.

2018-02-23 20:54 UTC, cmltaWt0 commented on deploy-clean.sh
> +sudo rm -rf .volumes
P.S. I do not want to run this on my PC with sudo :/

2018-02-23 20:54 UTC, rimikt commented on .dc-prod/docker-compose.yml
> +      - 8000:80
Is is the suggestion from Ops?

2018-02-23 20:55 UTC, rimikt commented
@sidorovdmitry Why do we need to proxy 80 to 8000 post on host?

2018-02-26 09:35 UTC, KhaimovMR commented on deploy-clean.sh
> +sudo rm -rf .volumes
sudo is here because of the permissions of the files, located in the .volumes/postgres (you can't delete them without those)

2018-02-26 09:36 UTC, KhaimovMR commented on .dc-prod/docker-compose.yml
> +      - 8000:80
Yes, it is.

2018-02-26 09:53 UTC, KhaimovMR commented on deploy-clean.sh
> +cd `dirname $(readlink -f $0)`/.dc-$DCENV
changed to the `realpath`, should be working now

2018-02-26 09:54 UTC, KhaimovMR commented on deploy-clean.sh
> +sudo rm -rf .volumes
`sudo` removing made by absolute path now
removed `sudo` from the `docker-compose up -d` command

2018-02-26 21:33 UTC, rimikt commented
@dgamanenko Any comments on this?

2018-02-27 10:05 UTC, dgamanenko approved these changes

2018-02-27 10:06 UTC, cmltaWt0 approved these changes

2018-02-27 10:07 UTC, merged